codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        # Minimum coverage ratio to be considered a success
        target: 70%
        # Allow coverage to drop by X% and still posting a success status
        threshold: 5%
        # Target to check against base branch
        base: auto
        # Only post a status if coverage exists for all files
        if_not_found: success
        # How many builds in a row are allowed to be skipped
        if_ci_failed: error
        # Only informational can never fail the build
        informational: false
        # Make status notification only from source files that match this paths
        paths:
          - "src/"
        # Exclude files from coverage that match these paths
        paths_ignore:
          - "tests/"
          - "vendor/"
    
    # Per patch coverage
    patch:
      default:
        # Minimum coverage ratio to be considered a success
        target: 70%
        # Allow coverage to drop by X% and still posting a success status
        threshold: 5%
        if_not_found: success
        if_ci_failed: error
        informational: false

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes
  branches: null
